### ISSUE TITLE
Color picker is always set to hexstring when opened

### ISSUE THREAD

**Issue by The-Force** [Denis-net/json-colors#2]
When I open the color picker, the actual value is displayed above with the correct format, but when I click to change the color it generates a hexadecimal string and I have to click several times to change the format. After I change the format manually it doesn't change anymore until I reopen it.

**Comment by Denis-net** [comment]
Hey @The-Force ! 😊👋🏼

This is the first known issue.
Unfortunately, this is a matter of string comparison and float to int conversion (i.e. precision loss):

VSC has its color components in decimal format.
The ColorProvider which i extend, expose me two methods:
1) at random it call my first method passing me the document and asking me to locate colors in it, so my regex spot colors and i compose ranges (i tell it: from position to position you can find this color)
2) when user hover over a color, VSC call the second method passing a VSC color that when converted back to the reppresented format got slighty changed because of the precision, and when i compose for each color its rappresentations i can only return a list to VSC.

The VSC picker is not accessible to developers and it changes the color presentation when it feels right to do so or when the user changes it.

My advice is: focus on the desired color without thinking about its presentation, then when you are happy chose the right format.

Otherwise you shoud try [this masterpiece of an extension](https://marketplace.visualstudio.com/items?itemName=RoyAction.color-manager).
My extension is more decorative: it allows you to spot colors without enter the Matrix👨🏼‍💻

I tried to find the css built-in extension, but without luck, so i have improvised.

**Comment by Denis-net** [comment]
With the right questions comes the right answers:
I was wrong about this issue, because when the user picks a color the picker set the decimal parts of the VSC color and then it calls my method but the document remains the same (with the old color),
when i compose the presentation i can't find any text matching the document because the color is changed.
I didn't think about this obvious thing, and for this reason i couldn't find the right presentation so i always returned the array sorted with the hexstring first (and the first presentation is the one you see at the top of the picker dialog).

With v0.0.5 you should experience a more reliable behaviour.👍🏼

**Comment by The-Force** [comment]
Yes now its working really great, just one thing, when in [RRR,GGG,BBB,AAA] alpha is less than 255 but greater than 1 the picker doesn't detect the format and uses the default one or the last one used.

**Comment by Denis-net** [comment]
I investigated and it's a precision loss issue.
With Regex i spot colors, but i need to validate using a colorConverter that provides R G B A components.
This converter can only converts rgba(rrr,ggg,bbb,a.aa) format, so i need to wrap and convert "RRR GGG BBB AAA" into that format.
Then i need to pass to VSC the color components detected by the converter.

In the 2 method (when the user is hovering over a color) VSC pass me the r,g,b,a.a components,
The issue here is that when converting back the a.a into AAA part it gets rounded (because sometimes you'll get AAA.aaaaaa and that even if would be more precise it would break the rule "0 <= A >= 255" , so i have to round the value.
And this is the problem's core:
`255,255,255,124`
after the two methods became
`255,255,255,124.95`
rounded to:
`255,255,255,125`

and in the color rappresentation detection "255,255,255,125" is different from "255,255,255,124".

What i have done in the version 0.0.6 is: if you have no match try to detect the format `RRR,GGG,BBB,AAA` and if it's successful use that format.

> In conclusion `255,255,255,124` will become `255,255,255,125` in the color presentation, but you'll get the correct color presentation.
This is a little compromise but it won't damage the color and will provide a better experience. 👍🏼

Let me know if it works on your end too.

**Comment by The-Force** [comment]
It works! As you say, some values change a little but that's close enough for me.

Now the workflow is very smooth. Again, thank you very much.
